# Generated by Django 5.1.2 on 2024-12-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.categorie'),
        ),
    ]
